name: Continuous Integration

on:
  pull_request:
    branches: ["main"]

jobs:
  ci_verification:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test Admin Service
        working-directory: ./admin-service
        run: |
          npm ci
          npm test

      - name: Test Customer Service
        working-directory: ./customer-service
        run: |
          npm ci
          npm test

      - name: Test Delivery Service
        working-directory: ./delivery-service
        run: |
          npm ci
          npm test

      - name: Test Movie Service
        working-directory: ./movies-service
        run: |
          npm ci
          npm test

      - name: Test Notification Service
        working-directory: ./notification-service
        run: |
          npm ci
          npm test

      - name: Test Payment Service
        working-directory: ./payment-service
        run: |
          npm ci
          npm test

      - name: Test Shopping Service
        working-directory: ./shopping-service
        run: |
          npm ci
          npm test